### ISSUE TITLE
Error while configuring CMake with USE_PNG and USE_Jasper ON and BUILD_SHARED_LIBS ON options.

### ISSUE THREAD

**Issue by joerengara** [eengl/homebrew-nceplibs#1]
==> cmake . -DUSE_PNG=ON -DUSE_Jasper=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_PREFIX_PATH=/opt/homebrew/Cellar/nceplibs-g2c/1.7.0
Last 15 lines from /Users/louoberto/Library/Logs/Homebrew/nceplibs-g2c/01.cmake:

      stderr: 
        /opt/homebrew/Library/Homebrew/shims/mac/super/pkg-config: line 12: /opt/homebrew/opt/pkg-config/bin/pkg-config: No such file or directory
      /opt/homebrew/Library/Homebrew/shims/mac/super/pkg-config: line 12: exec: /opt/homebrew/opt/pkg-config/bin/pkg-config: cannot execute: No such file or directory
      result: 

  126

Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.26.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.26.1/share/cmake/Modules/FindPkgConfig.cmake:99 (find_package_handle_standard_args)
  CMakeLists.txt:49 (find_package)

-- Configuring incomplete, errors occurred!

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/eengl/homebrew-nceplibs/issues

**Comment by eengl** [comment]
This is most likely due to pkg-config not being installed.  pkg-config should be a build dependency.

This should be fixed with https://github.com/eengl/homebrew-nceplibs/commit/52bb6774b86d95a456b7fbd1e3c196893be0d098
